name = "project"
skipFolders = [ "node_modules", ".vscode", "out", "dist", ".vscode-test" ]
skipFiles = [ ".gitignore", "package.json" ]

[[processes]]
id = "process1"
name = "To Do"
tasks = [ ]

[[processes]]
id = "process2"
name = "In Progress"

  [[processes.tasks]]
  id = "qxhdg1h4i935gpdizl048iea"
  title = "Plan scope and task distribution for project"
  description = ""
  tag = "backlog"
  linkFiles = [ ]
  dueDate = "10/15/2024"
  checkList = [ ]
  priority = ""
  linkCommits = [ ]

[[processes]]
id = "process3"
name = "Done"

  [[processes.tasks]]
  id = "rhpi3m735dxygbgvgjzeqx1c"
  title = "Initialize KanPilot"
  description = ""
  tag = "backlog"
  linkFiles = [ ]
  dueDate = "10/10/2024"
  checkList = [ ]
  priority = ""
  linkCommits = [ ]

  [[processes.tasks]]
  id = "fm9g3hni0v7fqav0tl28wyux"
  title = "met to build project base"
  description = "Built most of project base, working toward containerizing the project so that it can run crossplatform on mac due to owl issues."
  tag = "backlog"
  linkFiles = [ ]
  dueDate = "10/21/24"
  checkList = [ ]
  priority = ""
  linkCommits = [ ]
