version: '3.8'

services:
  calculator_app:
    build: .
    container_name: calculator_app_container
    volumes:
      - .:/app
    stdin_open: true  # Keeps STDIN open for interactive input
    tty: true         # Allocates a pseudo-TTY
    command: opam exec -- bash -c "dune build && dune exec calculator"
